export const START_FETCHING_STUDENTS = 'redux/students/START_FETCHING_STUDENTS'
export const SUCCESS_FETCHING_STUDENTS = 'redux/students/SUCCESS_FETCHING_STUDENTS'
export const ERROR_FETCHING_STUDENTS = 'redux/students/ERROR_FETCHING_STUDENTS'
export const SET_KEYWORD = 'redux/students/SET_KEYWORD'
export const SET_STUDY_PROGRAM = 'redux/students/SET_STUDY_PROGRAM'
export const SET_PAGE = 'redux/students/SET_PAGE'
